# Generated by Django 5.1.4 on 2024-12-18 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('food', models.CharField(max_length=100)),
                ('habitat', models.CharField(max_length=100)),
                ('speciality', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AnimalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='animal_images/')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='main.animal')),
            ],
        ),
    ]
