# Generated by Django 5.1.4 on 2025-01-01 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_animal_image_delete_animalimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='speciality',
            new_name='details',
        ),
    ]
