# Generated by Django 5.1.4 on 2025-01-04 22:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_speciality_animal_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='documentary_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
