# Generated by Django 5.1.4 on 2025-01-07 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_animal_documentary_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='habitat',
            field=models.CharField(max_length=500),
        ),
    ]
